### ISSUE TITLE
Add an option to respect Do Not Track header

### ISSUE THREAD

**Issue by MikkCZ** [deconf/Google-Analytics-Dashboard-for-WP#102]
It would be nice to have an opt-in option to respect [Do No Track](https://www.mozilla.org/firefox/dnt/) header. When checked in the admin, the plugin won't include the GA code in the page when the Do Not Track header is sent with the request.

**Comment by deconf** [comment]
Hi,

Thanks for the feedback! Google Analytics already provides means to opt-out, so instead of trying to support each browser/privacy solution I prefer to leverage that on the Google Analytics itself and its own methods of providing opt-out.

An user can be opted out programmatically with a simple line of JavaScript code (by an website owner). In addition, there are multiple privacy add-ons which allow this.

In my opinion, all those concerned about user privacy should come to a common sens and follow an agreed method instead of each one reinventing the wheel over and over again.

Most probably when things will turn out bad, as afs did, they will start working together and find an unanimous solution as they did with Coalition for better ads (https://www.betterads.org)

**Comment by MikkCZ** [comment]
GA is not about ads, so I am not sure if it will be addressed here.

DNT is actually not Mozilla specific, my bad I added link to their website only. The header is implemented AFAIK in every browser and available for the user to enable. Do you know if GA respects that header? I know it's easy to implement this for the website owner, but I would still suggest to add this feature directly in the plugin, especially if it's so easy. ;) If I have time, I may look at the code and create a PR myself. I guess the opt-out scenario may work the same way as exception by roles, just much simpler by checking the header instead of the user role.

**Comment by deconf** [comment]
The ads part was an example of common sense, unrelated, but which could work for tracking related issues.

**Comment by deconf** [comment]
Please do, patches are welcome! And if it's largely adopted I would be more than happy to provide such an option.

**Comment by MikkCZ** [comment]
I have found that GA has a mechanism to honor DNT header (http://www.outfox.com/do-not-track-for-google-analytics/). But I would prefer to not include GA code at all in case DNT header is sent (of course if the blog admin enables the option to honor DNT).

**Comment by deconf** [comment]
I saw that too, but I would prefer not to include any additional scripts and not relying on third party solutions at all. It will just add weight to the webpages and have a negative impact on loading speeds.

**Comment by deconf** [comment]
Hi,

We've implemented DNT for Analytics . We'll keep this open until we find a solution for all other components.

**Comment by MikkCZ** [comment]
Is [this](https://github.com/deconf/Google-Analytics-Dashboard-for-WP/commit/ce6196ea00dfffa11b79aa77c6c31dd073b6a726) the change where it has been implemented? I know I am not the owner of the code, but I have to say it seems to me as an overly complicated mechanism.
- In the solution currently in master, you also have several IFs and to be honest, the ones in `front/views/analytics-optout-code.php` are utterly unreadable. Moving those statements in brackets to  variables would definitely help to understand the meaning of the conditions.
- The cookies is set to a specific point in time, that's not good. I cannot find in the code what happens if the user disables the DNT feature. Is the "consent" with tracking honored? In the code in my PR there is no persistent cookie and instead the whole GA script is skipped on the client. Also some users may consider setting this cookies as tracking and dishonor of their DNT preference, and downloading the GA script also doesn't look respectful.
- What is the difference between `ga_optout` and `ga_dnt_optout` options?

P. S. The cookie in `gaOptout()` is actually never set - the function is never called. Why is it there?

**Comment by deconf** [comment]
Skipping the code is not a generally applicable solution. The way the feature was finally implemented will cover three technologies, allowing the user to opt-out by setting DNT from all GA tracking, no matter if gtag.js or analytics.js is used and no matter if the tracking code is inserted directly on the page or if Google Tag Manager is used.

The GTM opt-out code just passed the beta testings and will be submitted on the following days to the master.

Since there is no known way to opt out on AMP pages, we're going to close this issue.
