### ISSUE TITLE
Proxy settings for Curl

### ISSUE THREAD

**Issue by pixelFred** [deconf/Google-Analytics-Dashboard-for-WP#90]
Hi,
The WordPress proxy settings are apparently not used by the plugin. That's a problem for me because I can't use it without this settings.
I found a way to pass the parameters to the Curl library by adding this lines in **tools/gapi.php** before line 44 :
```
if (defined('WP_PROXY_HOST') && defined('WP_PROXY_PORT')) {
	$curl_options[CURLOPT_PROXY] = WP_PROXY_HOST.":".WP_PROXY_PORT;
}
```
Is it possible to include this enhancement in a future release please?

**Comment by deconf** [comment]
Hi,

You can set your own cURL options through the *gadwp_curl_options* filter.

For details see https://github.com/deconf/Google-Analytics-Dashboard-for-WP/pull/85

**Comment by pixelFred** [comment]
Ok, thank you for your quick reply. I understand that and that works fine with the filter. But it's not very intuitive and I have to add the filter to all my websites. 

With my suggestion, all users who have a WordPress behind a proxy and have already configured it in their wp-config.php file (I think it's not so rare) have nothing more to do to use the plugin.
Without that you have to figure out why GADWP cannot connect to the Google Analytics server (the other plugins I use are working well without a specific configuration to pass the proxy...).

**Comment by deconf** [comment]
I understand, but for rare use cases I provide filters instead of cluttering the interface with meaningless features for the majority of users.

In over 3 years I had only two requests for this feature. One is from a government institutions (which needs a proxy for obvious reasons) and you.

So the use case is quite rare, and when there's a problem I'm dealing with experts that know exactly what's the culprit and have advanced knowledge of WordPress and programing in general. (as you probably do).

**Comment by pixelFred** [comment]
Ok I understand your point of view, no problem. I will use the filter solution.
Thank you

**Comment by deconf** [comment]
Thank you and thanks for the feedback!
