### ISSUE TITLE
Chart Not Loading

### ISSUE THREAD

**Issue by adampatarino** [deconf/Google-Analytics-Dashboard-for-WP#91]
Since the most recent update, the chart no longer loads on the dashboard. I've unlinked and relinked the account. Deleted and resintalled the plugin, etc. 

I'm seeing this error in the console: https://cl.ly/1b2w1d32433h

```
Uncaught TypeError: Cannot read property 'arrayToDataTable' of undefined     reports.js:402
```

WP Version 4.6.1
Plugin Version 4.9.6

**Comment by deconf** [comment]
Hi, it's not a bug, most common cases are because of plugin conflicts.

First thing first, you should follow the steps described in the FAQ page regarding issues after updates.

If that doesn't work, check if there are any plugin conflicts. You need to disable all other plugins, and re-enable them one by one until you identify the one generating the issue.

**Comment by adampatarino** [comment]
Thanks for your help. It wasn't a plugin conflict, but clearing cache and storage seemed to fix the issue. Thank you!
